### ISSUE TITLE
error fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by inferi0n** [jescalan/roots#759]
Hi!
I have problem. I've tried to install sprout static-cms, and when i run `npm i` i see this error.
I tried run command line with -root, and tried `npm cache clean` but this both methods didn't work.
It seem like problem in that there is no repo jenius/st. Can you help me, please?

`verbose stack Error: Command failed: git -c core.longpaths=true clone C:\Users\Руслан\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jenius-st-git-f0888ef5 C:\Users\Руслан\AppData\Local\Temp\npm-4960-a499b128\git-cache-77000f08\c26142ba1060706b8585917716b5e9c7999ef50a
15937 verbose stack Cloning into 'C:\Users\Руслан\AppData\Local\Temp\npm-4960-a499b128\git-cache-77000f08\c26142ba1060706b8585917716b5e9c7999ef50a'...
15937 verbose stack "git-upload-pack 'C:\Users\Руслан\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jenius-st-git-f0888ef5'": git-upload-pack 'C:\Users\Руслан\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jenius-st-git-f0888ef5': No such file or directory
15937 verbose stack fatal: Could not read from remote repository.
15937 verbose stack
15937 verbose stack Please make sure you have the correct access rights
15937 verbose stack and the repository exists.
15937 verbose stack
15937 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
15937 verbose stack     at emitTwo (events.js:106:13)
15937 verbose stack     at ChildProcess.emit (events.js:191:7)
15937 verbose stack     at maybeClose (internal/child_process.js:877:16)
15937 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15938 verbose cwd D:\workflow\projects\roots\contentful-test-blog
15939 error Windows_NT 6.1.7601
15940 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
15941 error node v6.9.1
15942 error npm  v3.10.8
15943 error code 128
15944 error Command failed: git -c core.longpaths=true clone C:\Users\Руслан\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jenius-st-git-f0888ef5 C:\Users\Руслан\AppData\Local\Temp\npm-4960-a499b128\git-cache-77000f08\c26142ba1060706b8585917716b5e9c7999ef50a
15944 error Cloning into 'C:\Users\Руслан\AppData\Local\Temp\npm-4960-a499b128\git-cache-77000f08\c26142ba1060706b8585917716b5e9c7999ef50a'...
15944 error "git-upload-pack 'C:\Users\Руслан\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jenius-st-git-f0888ef5'": git-upload-pack 'C:\Users\Руслан\AppData\Roaming\npm-cache\_git-remotes\git-github-com-jenius-st-git-f0888ef5': No such file or directory
15944 error fatal: Could not read from remote repository.
15944 error
15944 error Please make sure you have the correct access rights
15944 error and the repository exists.
15945 error If you need help, you may report this error at:
15945 error     <https://github.com/npm/npm/issues>
15946 verbose exit [ 1, true ]`

**Comment by jescalan** [comment]
Hi there @inferi0n -- this is an issue with sprout-static-cms and not roots, so I'd report it over there. Chances are this repo is unmaintained though, I must warn you!
